# this is the availability settings for proxus
#[reconnect]
# number of seconds between retrying connection - defaults to 5
# 0 is valid but extremely laggy
retry_time = 1
# number of times reconnection can be attempted before the thread is closed
watchdog_timer = 5000
# if the connection has been re-established, should the counter be reset
reset_after_success = true


# if you want proxus to simply retry connectioning, just add 
[reconnect]
# ^ this will retry every 5 seconds, with no watchdog


# standard config for proxus - connects a domain name or IP address & port 
# example result
# localhost:9090 <-> 192.168.1.1:9091
[[data]]
a1 = "localhost:9090"
a2 = "192.168.1.1:9091"

# port bind - bridge many ports together on different IP addreses
# example result
# localhost:9090 <-> 192.168.1.1:9090
# localhost:9091 <-> 192.168.1.1:9091
[[data]]
ip = ["localhost", "192.168.1.1"]
bind = [9090, 9091]

# bindcast - bridge many ports together but change the port number - the ports are connected based on the index of the array
# example result
# localhost:9091 <-> 192.168.1.1:9090
# localhost:443 <-> 192.168.1.1:8080
[[data]]
ip = ["localhost", "192.168.1.1"]
bind = [9091, 443]
cast = [9090, 8080]



# example of casting connection of freeipa directory service server to hypervisor
# 80 and 44 are reserved so they need to be casted to another port
[[data]]
ip = ["192.168.1.100", "192.168.122.58"]
bind = [80, 443]
cast = [8080, 8090]

# the rest are just forwarded
[[data]]
ip = ["192.168.1.100", "192.168.122.58"]
bind = [8, 464, 636, 88, 464, 123]

