# domain names or IP addresses can be used
# multiple entries are valid under the name 'data'
[[data]]
a1 = "domain.name:PORT"
a2 = "domain.name:PORT"

# simple example
#[[data]]
#a1 = "localhost:443"
#a2 = "192.168.54.211:443"

